spring.application.name=textileSys

spring.datasource.url=jdbc:mysql://localhost:3306/textile_db
spring.datasource.username=root
spring.datasource.password=2549

# Fix: Serialize LocalDate as "2024-09-18" string instead of [2024,9,18] array
#spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
