import React, { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Edit2, Package, Plus, Trash2, Save } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { api } from '../services/api';
import { Modal } from '../components/Modal';
import { IssueYarnPickerModal } from '../components/IssueYarnPickerModal';

const today = () => new Date().toISOString().slice(0, 10);
const blank = () => ({ challanNo: `WFT-${Date.now()}`, firmName: '', internalGatepassNo: '', partyGatepassNo: '', dispatchDate: today(), beamSerialNo: '', previousSetNo: '', remarks: '' });

export const WeftDispatchView = () => {
  const { addToast } = useApp();
  const [sets, setSets] = useState([]); const [records, setRecords] = useState([]);
  const [header, setHeader] = useState(blank()); const [setId, setSetId] = useState('');
  const [stock, setStock] = useState([]); const [items, setItems] = useState([]);
  const [modal, setModal] = useState(false); const [query, setQuery] = useState(''); const [sourceFilter, setSourceFilter] = useState('all'); const [loadingStock, setLoadingStock] = useState(false); const [busy, setBusy] = useState(false);
  const [formOpen, setFormOpen] = useState(false); const [editing, setEditing] = useState(null);
  const [beams, setBeams] = useState([]);
  useEffect(() => { Promise.allSettled([api.sizingSets.getAll(), api.weftDispatches.getAll()]).then(([s,r]) => { if(s.status==='fulfilled') setSets(Array.isArray(s.value)?s.value.filter(x=>x.status!=='DELETED'):[]); if(r.status==='fulfilled') setRecords(Array.isArray(r.value)?r.value:[]); }); }, []);
  const selectedSet = sets.find(x => String(x.sizingSetId) === String(setId));
  useEffect(() => {
    const firmName = selectedSet?.order?.supplier?.partyName || selectedSet?.orderFirmName || '';
    setHeader(previous => ({ ...previous, firmName }));
  }, [selectedSet]);
  useEffect(() => { if (!setId) { setBeams([]); setHeader(previous=>({...previous,beamSerialNo:''})); return; } api.beamInward.getBySizingSet(setId).then(rows=>setBeams((Array.isArray(rows)?rows:[]).filter(beam=>!['DELETED','COMPLETED','USED','CONSUMED'].includes(String(beam.status||'').toUpperCase())))).catch(()=>setBeams([])); }, [setId]);
  const openNew = () => { setEditing(null); setHeader(blank()); setSetId(''); setItems([]); setFormOpen(true); };
  const openEdit = record => {
    setEditing(record);
    setSetId(String(record.sizingSet?.sizingSetId || sets.find(s => s.setNo === record.setNo)?.sizingSetId || ''));
    setHeader({challanNo:record.challanNo||'',firmName:record.firmName||'',internalGatepassNo:record.internalGatepassNo||'',partyGatepassNo:record.partyGatepassNo||'',dispatchDate:record.dispatchDate||today(),beamSerialNo:record.beamSerialNo||'',previousSetNo:record.previousSetNo||'',remarks:record.remarks||''});
    setItems((record.lines||[]).map(line=>({sourceType:line.sourceType,sourceId:line.sourceId,serial:line.serialLabel,count:line.countName,ticket:line.ticketName,mill:line.millName,shade:line.shade,packageType:line.packageType,issuedBags:Number(line.issuedBags||0),issuedPackages:Number(line.issuedPackages||0),grossWeight:Number(line.grossWeightKg||0),calculatedWeight:Number(line.calculatedWeightKg||0),availableBags:Number(line.issuedBags||0),availableWeight:Number(line.grossWeightKg||0)})));
    setFormOpen(true);
  };
  const fetchStock = async () => {
    setLoadingStock(true);
    try {
      const [raw, returned] = await Promise.all([api.yarnInward.getAll(), api.sizingYarnInward.getAll()]);
      const a=raw.filter(x=>Number(x.bags||0)>0).map(x=>({id:x.yarnInwardId,key:`yarn-${x.yarnInwardId}`,sourceType:'yarnIn',sourceLabel:String(x.type||'FRESH').toUpperCase()==='DYED'?'Dyed Yarn':'Fresh Yarn',type:String(x.type||'FRESH').toUpperCase(),setNo:'-',serialLabel:x.billNo||`YI-${x.yarnInwardId}`,countName:x.count?.countName||x.count?.countNo||'-',tickitName:x.tickit?.tickitName||x.tickit?.tickitNo||'-',supplierName:x.supplier?.partyName||x.storageParty?.partyName||'-',inwardDate:x.inwardDate||'',remainingBags:Number(x.bags||0),cones:Number(x.yCone||0),weightPerBag:Number(x.weightKg||0)/Number(x.bags||1),weightKg:Number(x.weightKg||0),checked:false,issueBags:'',issueCones:'',issueWeightKg:0}));
      const b=returned.filter(x=>Number(x.bags||0)>0).map(x=>({id:x.sizingInwardId,key:`sizing-${x.sizingInwardId}`,sourceType:'sizingIn',sourceLabel:'Returned Yarn',type:'RETURNED',setNo:x.sizingSet?.setNo||'-',serialLabel:`SIn ${x.sizingInwardId}`,countName:x.count?.countName||x.count?.countNo||'-',tickitName:x.tickit?.tickitName||x.tickit?.tickitNo||'-',supplierName:x.party?.partyName||x.sizingUnit?.sizingName||'-',inwardDate:x.inwardDate||'',remainingBags:Number(x.bags||0),cones:0,weightPerBag:Number(x.weightKg||0)/Number(x.bags||1),weightKg:Number(x.weightKg||0),checked:false,issueBags:'',issueCones:'0',issueWeightKg:0}));
      setStock([...a,...b]);setQuery('');setSourceFilter('all');setModal(true);
    } catch(e){addToast(e.message||'Unable to load yarn stock','error');} finally{setLoadingStock(false);}
  };
  const filtered=stock.filter(x=>(sourceFilter==='all'||x.sourceType===sourceFilter)&&`${x.serialLabel} ${x.setNo} ${x.countName} ${x.tickitName} ${x.supplierName} ${x.inwardDate}`.toLowerCase().includes(query.toLowerCase()));
  const toggle=(key,checked)=>setStock(rows=>rows.map(x=>x.key!==key?x:{...x,checked,issueBags:checked?String(x.remainingBags):'',issueCones:checked?String(x.cones):'',issueWeightKg:checked?x.weightKg:0}));
  const changeBags=(key,value)=>setStock(rows=>rows.map(x=>{if(x.key!==key)return x;if(value==='')return {...x,issueBags:'',issueWeightKg:0};const n=Math.max(0,Math.min(Number(value)||0,x.remainingBags));return {...x,issueBags:String(n),issueWeightKg:n*x.weightPerBag};}));
  const changeCones=(key,value)=>setStock(rows=>rows.map(x=>x.key!==key?x:{...x,issueCones:value===''?'':String(Math.max(0,Math.min(Number(value)||0,x.cones)))}));
  const confirmRows=()=>{const chosen=stock.filter(x=>x.checked);if(!chosen.length){addToast('Select at least one yarn lot','warning');return;}if(chosen.some(x=>Number(x.issueBags)<=0||Number(x.issueBags)>x.remainingBags||Number(x.issueCones)<0||Number(x.issueCones)>x.cones)){addToast('Enter valid bags and cones within available stock','error');return;}setItems(chosen.map(x=>({sourceType:x.sourceType==='yarnIn'?'RAW':'SIZING_RETURN',sourceId:x.id,serial:x.serialLabel,count:x.countName,ticket:x.tickitName,mill:x.supplierName,shade:'Grey/Cotton',packageType:'Cones',issuedBags:Number(x.issueBags),issuedPackages:Number(x.issueCones||0),grossWeight:Number(x.issueWeightKg||0),calculatedWeight:Number(x.issueWeightKg||0),availableBags:x.remainingBags,availableWeight:x.weightKg})));setModal(false);};
  const totals = useMemo(()=>items.reduce((a,x)=>({bags:a.bags+x.issuedBags,weight:a.weight+x.grossWeight}),{bags:0,weight:0}),[items]);
  const submit = async e => { e.preventDefault(); if(!selectedSet){addToast('Select a Set No','error');return;} if(!header.firmName.trim()){addToast('Enter the firm name','error');return;} if(!items.some(x=>Number(x.grossWeight)>0)){addToast('At least one yarn row with weight greater than zero is required','error');return;} if(items.some(x=>!Number.isFinite(Number(x.grossWeight))||Number(x.grossWeight)<=0)){addToast('Every selected yarn row must have weight greater than zero','error');return;} setBusy(true); try { const payload={...header,sizingSetId:selectedSet.sizingSetId,setNo:selectedSet.setNo,quality:selectedSet.quality||'',weaverPartyName:selectedSet.order?.party?.partyName||selectedSet.party?.partyName||'',lines:items.map(x=>({...x}))}; if(editing) await api.weftDispatches.update(editing.weftDispatchId,payload); else await api.weftDispatches.create(payload); addToast(editing?'Weft dispatch updated and stock adjusted':'Weft dispatch challan saved and stock updated','success'); setFormOpen(false);setEditing(null);const r=await api.weftDispatches.getAll();setRecords(Array.isArray(r)?r:[]); } catch(err){addToast(err.message||'Failed to save weft dispatch','error');} finally{setBusy(false);} };
  const remove = async record => { if(!window.confirm(`Delete dispatch ${record.challanNo}? Issued stock will be restored.`))return; try{await api.weftDispatches.delete(record.weftDispatchId);addToast('Dispatch deleted and stock restored','success');const r=await api.weftDispatches.getAll();setRecords(Array.isArray(r)?r:[]);}catch(e){addToast(e.message||'Failed to delete dispatch','error');} };
  const markCompleted = async record => { try { await api.weftDispatches.setStatus(record.weftDispatchId,'COMPLETED'); const r=await api.weftDispatches.getAll();setRecords(Array.isArray(r)?r:[]);addToast('Dispatch marked completed','success'); } catch(e) { addToast(e.message||'Could not update dispatch status','error'); } };
  const selectPreviousSet = value => {
    setHeader(previous=>({...previous,previousSetNo:value}));
    const previousDispatch=records.filter(record=>record.setNo===value).sort((a,b)=>String(b.dispatchDate||'').localeCompare(String(a.dispatchDate||'')))[0];
    const carryItems=(previousDispatch?.lines||[]).map(line=>({sourceType:'TRANSFER',sourceId:line.weftDispatchLineId,serial:line.serialLabel||`Carry-${line.weftDispatchLineId}`,count:line.countName||'-',ticket:line.ticketName||'-',mill:line.millName||'-',shade:line.shade||'Grey/Cotton',packageType:line.packageType||'Cones',issuedBags:Number(line.issuedBags||0),issuedPackages:Number(line.issuedPackages||0),grossWeight:Number(line.grossWeightKg||0),calculatedWeight:Number(line.calculatedWeightKg||line.grossWeightKg||0),availableBags:Number(line.issuedBags||0),availableWeight:Number(line.grossWeightKg||0)}));
    setItems(current=>[...current.filter(line=>line.sourceType!=='TRANSFER'),...carryItems]);
  };
  return <div className="content-area"><div className="section-card"><div className="section-card-header"><div className="section-card-title"><Package size={20} color="var(--primary-blue)"/><div><h3 style={{margin:0}}>Yarn Issue to Weaving</h3><span style={{fontSize:'.8rem',color:'var(--text-muted)'}}>Recent weft dispatches</span></div></div><button type="button" className="btn btn-primary" onClick={openNew}><Plus size={16}/> New Weaving</button></div>
    <div className="table-responsive" style={{marginTop:20}}><table className="data-table"><thead><tr><th>Set No</th><th>Weaver / Loom Party</th><th>Dispatch Date</th><th>Internal Gatepass</th><th>Total Bags</th><th>Total Weight</th><th>Status</th><th>Actions</th></tr></thead><tbody>{records.length ? records.map(x=><tr key={x.weftDispatchId}><td>{x.setNo||'-'}</td><td>{x.weaverPartyName||'-'}</td><td>{x.dispatchDate||'-'}</td><td>{x.internalGatepassNo||'-'}</td><td>{(x.lines||[]).reduce((sum,line)=>sum+Number(line.issuedBags||0),0).toFixed(3)}</td><td>{Number(x.totalWeightKg||0).toFixed(3)} kg</td><td><span className={`badge ${String(x.status||'ISSUED').toUpperCase()==='COMPLETED'?'badge-success':'badge-warning'}`}>{String(x.status||'ISSUED').toUpperCase()}</span></td><td><div style={{display:'flex',gap:6}}>{String(x.status||'').toUpperCase()!=='COMPLETED'&&<button type="button" className="btn-icon" title="Mark completed" onClick={()=>markCompleted(x)}><CheckCircle2 size={15}/></button>}<button type="button" className="btn-icon" title="Edit dispatch" onClick={()=>openEdit(x)}><Edit2 size={15}/></button><button type="button" className="btn-icon" title="Delete dispatch" style={{color:'var(--color-danger)'}} onClick={()=>remove(x)}><Trash2 size={15}/></button></div></td></tr>) : <tr><td colSpan="8" style={{textAlign:'center',padding:28,color:'var(--text-muted)'}}>No weft dispatches found.</td></tr>}</tbody></table></div></div>
    <Modal isOpen={formOpen} onClose={()=>setFormOpen(false)} title={editing?'Edit Weaving Dispatch':'New Weaving'} size="lg"><form onSubmit={submit}><div className="form-grid-4">
      <div className="form-group"><label>Set No *</label><select className="form-control" value={setId} onChange={e=>{setSetId(e.target.value);setItems([]);}} required><option value="">Select Set No</option>{sets.map(s=><option key={s.sizingSetId} value={s.sizingSetId}>{s.setNo}</option>)}</select></div>
      <div className="form-group"><label>Firm Name *</label><input className="form-control" value={header.firmName} readOnly placeholder="Auto-filled from sizing set" required/></div>
      <div className="form-group"><label>Quality Specification</label><input className="form-control" readOnly value={selectedSet?.quality||''}/></div>
      <div className="form-group"><label>Weaver Party</label><input className="form-control" readOnly value={selectedSet?.order?.party?.partyName||selectedSet?.party?.partyName||editing?.weaverPartyName||''}/></div>
      <div className="form-group"><label>Internal Gatepass No *</label><input className="form-control" required value={header.internalGatepassNo} onChange={e=>setHeader({...header,internalGatepassNo:e.target.value})}/></div>
      <div className="form-group"><label>Dispatch Date *</label><input type="date" className="form-control" required value={header.dispatchDate} onChange={e=>setHeader({...header,dispatchDate:e.target.value})}/></div>
      <div className="form-group"><label>Beam Serial No</label><select className="form-control" value={header.beamSerialNo} onChange={e=>setHeader({...header,beamSerialNo:e.target.value})}><option value="">Select active beam</option>{beams.map(beam=><option key={beam.beamId} value={beam.beamNo||beam.flangeNo||beam.inwardNo}>{[beam.beamNo,beam.flangeNo&&`Flange ${beam.flangeNo}`,beam.status].filter(Boolean).join(' · ')}</option>)}</select></div>
      <div className="form-group"><label>Transfer From Previous Set No</label><select className="form-control" value={header.previousSetNo} onChange={e=>selectPreviousSet(e.target.value)}><option value="">None</option>{sets.filter(s=>s.sizingSetId!==selectedSet?.sizingSetId).map(s=><option key={s.sizingSetId} value={s.setNo}>{s.setNo}</option>)}</select></div>
      <div className="form-group" style={{gridColumn:'span 3'}}><label>Remarks</label><input className="form-control" value={header.remarks} onChange={e=>setHeader({...header,remarks:e.target.value})}/></div>
    </div>
    <div className="section-card" style={{marginTop:20}}><div className="section-card-header"><h4 style={{margin:0}}>Selected Weft Yarn</h4><button type="button" className="btn btn-secondary" onClick={fetchStock}><Plus size={15}/> Issue Yarn</button></div><div className="table-responsive weft-yarn-grid-wrap"><table className="data-table weft-yarn-grid"><colgroup><col style={{width:'12%'}}/><col style={{width:'13%'}}/><col style={{width:'9%'}}/><col style={{width:'10%'}}/><col style={{width:'9%'}}/><col style={{width:'11%'}}/><col style={{width:'10%'}}/><col style={{width:'10%'}}/><col style={{width:'10%'}}/><col style={{width:'6%'}}/></colgroup><thead><tr>{['Yarn Serial / Lot','Count & Ticket','Party Name','Shade / Color','Package Type','Issued Bags / Boxes','Issued Packages','Scale Weight (Kg)','Calculated Weight (Kg)',''].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{items.length?items.map((x,i)=><tr key={`${x.sourceType}-${x.sourceId}`}><td>{x.serial}</td><td>{x.count} / {x.ticket}</td><td>{x.mill}</td><td>{x.shade}</td><td><select className="form-control" value={x.packageType} onChange={e=>setItems(v=>v.map((z,j)=>j===i?{...z,packageType:e.target.value}:z))}><option>Cones</option><option>PIRN</option><option>Cheese</option></select></td><td><input type="number" min="0" max={x.availableBags} step=".001" className="form-control" value={x.issuedBags} onChange={e=>setItems(v=>v.map((z,j)=>j===i?{...z,issuedBags:Number(e.target.value),calculatedWeight:x.availableBags?Number(e.target.value)*z.availableWeight/z.availableBags:0}:z))}/><small>Avail {x.availableBags}</small></td><td><input type="number" min="0" className="form-control" value={x.issuedPackages} onChange={e=>setItems(v=>v.map((z,j)=>j===i?{...z,issuedPackages:Number(e.target.value)}:z))}/></td><td><input type="number" min="0" max={x.availableWeight} step=".001" className="form-control" value={x.grossWeight} onChange={e=>setItems(v=>v.map((z,j)=>j===i?{...z,grossWeight:Number(e.target.value)}:z))}/></td><td>{x.calculatedWeight.toFixed(3)}</td><td><button type="button" className="btn-icon" onClick={()=>setItems(v=>v.filter((_,j)=>j!==i))}><Trash2 size={15}/></button></td></tr>):<tr><td colSpan="10" style={{textAlign:'center',padding:24}}>Select warehouse yarn lots to begin dispatch.</td></tr>}</tbody></table></div><div style={{padding:14,textAlign:'right',fontWeight:700}}>Total Bags: {totals.bags.toFixed(3)} &nbsp; | &nbsp; Total Issued Weight: {totals.weight.toFixed(3)} Kg</div></div>
    <div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:16}}><button type="button" className="btn btn-secondary" onClick={()=>setFormOpen(false)}>Close</button><button className="btn btn-primary" disabled={busy}><Save size={16}/>{busy?'Saving...':editing?'Update Weft Dispatch':'Save Weft Dispatch'}</button></div></form></Modal>
  <IssueYarnPickerModal isOpen={modal} onClose={()=>setModal(false)} rows={filtered} loading={loadingStock} search={query} onSearchChange={setQuery} sourceFilter={sourceFilter} onSourceFilterChange={setSourceFilter} onToggle={toggle} onBagsChange={changeBags} onConesChange={changeCones} onDone={confirmRows} showSetNo />
  </div>;
};
export default WeftDispatchView;
